server:
  port: 0

spring:
  application:
    name: userService
  # MongoDB
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: user
      port: 27017
      host: localhost
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# JWT
jwt:
  secret:
    key: secret_secret_secret_secret_secret_secret_secret_secret
