<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Chi Tiết Vé</title>
</head>

<body>
<div align="center" width="100%" border="2px">
    <div align="center" valign="top">
        <br> <br>
        <div width="600" border="3px">
            <div style="font-size: 48px; color: black; font-family: Arial;">
                <b>Chi Tiết Vé</b>
            </div>

            <div style="font-size: 24px; color: black; font-family: Arial;">
                <br>
                    <b>Giao dịch thanh toán của bạn đã thành công</b>
                <br>
            </div>

            <div>
                <br> Kính gửi ${fullName}, cảm ơn bạn đã chọn BookingMovie để mua vé, <br>
                <br>
                <h3>Chi Tiết Vé</h3>
                <h4>${movieName}</h4>
                <br>
                <h5><b>Ngày: </b> ${movieDay} </h5>
                <h5><b>Rạp: </b> ${saloonName} </h5>
                <h5><b>Suất chiếu: </b> ${movieStartTime} </h5>
                <h5><b>Ghế: </b> ${chairNumbers} </h5>

            </div>
            <br>
            <div>
                <h4>BookingMovie kính chúc bạn có những giây phút xem phim vui vẻ!</h4>
            </div>
        </div>

        <br> <br>

    </div>
</div>
</body>
</html>
    </div>
</div>
</body>